
project_id = "jwzzkqelqsqsirfowevs"
# This should be kept as the first line of this file.
# Configuration for Edge Functions.

[functions.financial-advisor]
verify_jwt = false

[functions.new-blog-post]
verify_jwt = false

[functions.newsletter-signup]
verify_jwt = false
