import { useState, useEffect } from 'react';
import { supabase } from '@/integrations/supabase/client';
import { useAuth } from '@/contexts/AuthContext';
import { Debt } from '@/utils/calculator/types';

export function useDebts() {
    const { user } = useAuth();
    const [debts, setDebts] = useState<Debt[]>([]);
    const [loading, setLoading] = useState(true);

    // Load initial data
    useEffect(() => {
        async function loadData() {
            if (user) {
                // Fetch from Supabase
                const { data, error } = await (supabase
                    .from('debts' as any)
                    .select('*')
                    .order('created_at', { ascending: true }) as any);

                if (error) {
                    console.error('Error fetching debts:', error);
                } else if (data) {
                    // Map Supabase rows to Front-end Debt objects
                    const mappedDebts: Debt[] = (data as any[]).map(d => ({
                        id: d.id,
                        name: d.name,
                        balance: Number(d.balance),
                        interestRate: Number(d.interest_rate),
                        minimumPayment: Number(d.minimum_payment),
                        type: 'loan' // Default type if not stored
                    }));
                    setDebts(mappedDebts);
                }
            } else {
                // Fallback to LocalStorage for guests
                const stored = localStorage.getItem('loans'); // Note: 'loans' key from original code
                if (stored) {
                    try {
                        setDebts(JSON.parse(stored));
                    } catch (e) {
                        console.error('Error parsing local storage debts', e);
                    }
                }
            }
            setLoading(false);
        }

        loadData();
    }, [user]);

    // Save function
    const saveDebts = async (newDebts: Debt[]) => {
        // Optimistic update
        setDebts(newDebts);

        if (user) {
            // 1. Sync entire list to Supabase (Simplest approach: Delete all own debts & Insert new)
            // Note: A smarter diffing approach would be better for performance, but this ensures consistency.
            try {
                // Delete all existing debts for this user
                const { error: deleteError } = await (supabase
                    .from('debts' as any)
                    .delete()
                    .eq('user_id', user.id) as any); // RLS handles this anyway, but explicit is good

                if (deleteError) throw deleteError;

                if (newDebts.length > 0) {
                    const rowsToInsert = newDebts.map(d => ({
                        user_id: user.id,
                        name: d.name,
                        balance: d.balance,
                        interest_rate: d.interestRate,
                        minimum_payment: d.minimumPayment
                        // ID is auto-generated by DB or we can reuse if we tracked it properly
                    }));

                    const { error: insertError } = await (supabase
                        .from('debts' as any)
                        .insert(rowsToInsert) as any);

                    if (insertError) throw insertError;
                }
            } catch (error) {
                console.error('Error syncing to Supabase:', error);
                // Revert local state? Or just show toast?
            }
        } else {
            // Save to LocalStorage
            localStorage.setItem('loans', JSON.stringify(newDebts));
        }
    };

    return { debts, setDebts: saveDebts, loading };
}
